/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SortRouteImport } from './routes/sort'
import { Route as RowselectionRouteImport } from './routes/rowselection'
import { Route as PaginationRouteImport } from './routes/pagination'
import { Route as GlobalfilterRouteImport } from './routes/globalfilter'
import { Route as DefaultfilterRouteImport } from './routes/defaultfilter'
import { Route as CoulmnfilterRouteImport } from './routes/coulmnfilter'
import { Route as ColumnorderRouteImport } from './routes/columnorder'
import { Route as IndexRouteImport } from './routes/index'

const SortRoute = SortRouteImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => rootRouteImport,
} as any)
const RowselectionRoute = RowselectionRouteImport.update({
  id: '/rowselection',
  path: '/rowselection',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginationRoute = PaginationRouteImport.update({
  id: '/pagination',
  path: '/pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalfilterRoute = GlobalfilterRouteImport.update({
  id: '/globalfilter',
  path: '/globalfilter',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultfilterRoute = DefaultfilterRouteImport.update({
  id: '/defaultfilter',
  path: '/defaultfilter',
  getParentRoute: () => rootRouteImport,
} as any)
const CoulmnfilterRoute = CoulmnfilterRouteImport.update({
  id: '/coulmnfilter',
  path: '/coulmnfilter',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnorderRoute = ColumnorderRouteImport.update({
  id: '/columnorder',
  path: '/columnorder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/columnorder': typeof ColumnorderRoute
  '/coulmnfilter': typeof CoulmnfilterRoute
  '/defaultfilter': typeof DefaultfilterRoute
  '/globalfilter': typeof GlobalfilterRoute
  '/pagination': typeof PaginationRoute
  '/rowselection': typeof RowselectionRoute
  '/sort': typeof SortRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/columnorder': typeof ColumnorderRoute
  '/coulmnfilter': typeof CoulmnfilterRoute
  '/defaultfilter': typeof DefaultfilterRoute
  '/globalfilter': typeof GlobalfilterRoute
  '/pagination': typeof PaginationRoute
  '/rowselection': typeof RowselectionRoute
  '/sort': typeof SortRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/columnorder': typeof ColumnorderRoute
  '/coulmnfilter': typeof CoulmnfilterRoute
  '/defaultfilter': typeof DefaultfilterRoute
  '/globalfilter': typeof GlobalfilterRoute
  '/pagination': typeof PaginationRoute
  '/rowselection': typeof RowselectionRoute
  '/sort': typeof SortRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/columnorder'
    | '/coulmnfilter'
    | '/defaultfilter'
    | '/globalfilter'
    | '/pagination'
    | '/rowselection'
    | '/sort'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/columnorder'
    | '/coulmnfilter'
    | '/defaultfilter'
    | '/globalfilter'
    | '/pagination'
    | '/rowselection'
    | '/sort'
  id:
    | '__root__'
    | '/'
    | '/columnorder'
    | '/coulmnfilter'
    | '/defaultfilter'
    | '/globalfilter'
    | '/pagination'
    | '/rowselection'
    | '/sort'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColumnorderRoute: typeof ColumnorderRoute
  CoulmnfilterRoute: typeof CoulmnfilterRoute
  DefaultfilterRoute: typeof DefaultfilterRoute
  GlobalfilterRoute: typeof GlobalfilterRoute
  PaginationRoute: typeof PaginationRoute
  RowselectionRoute: typeof RowselectionRoute
  SortRoute: typeof SortRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sort': {
      id: '/sort'
      path: '/sort'
      fullPath: '/sort'
      preLoaderRoute: typeof SortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rowselection': {
      id: '/rowselection'
      path: '/rowselection'
      fullPath: '/rowselection'
      preLoaderRoute: typeof RowselectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagination': {
      id: '/pagination'
      path: '/pagination'
      fullPath: '/pagination'
      preLoaderRoute: typeof PaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globalfilter': {
      id: '/globalfilter'
      path: '/globalfilter'
      fullPath: '/globalfilter'
      preLoaderRoute: typeof GlobalfilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defaultfilter': {
      id: '/defaultfilter'
      path: '/defaultfilter'
      fullPath: '/defaultfilter'
      preLoaderRoute: typeof DefaultfilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coulmnfilter': {
      id: '/coulmnfilter'
      path: '/coulmnfilter'
      fullPath: '/coulmnfilter'
      preLoaderRoute: typeof CoulmnfilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/columnorder': {
      id: '/columnorder'
      path: '/columnorder'
      fullPath: '/columnorder'
      preLoaderRoute: typeof ColumnorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColumnorderRoute: ColumnorderRoute,
  CoulmnfilterRoute: CoulmnfilterRoute,
  DefaultfilterRoute: DefaultfilterRoute,
  GlobalfilterRoute: GlobalfilterRoute,
  PaginationRoute: PaginationRoute,
  RowselectionRoute: RowselectionRoute,
  SortRoute: SortRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
