/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParamsparameterRouteImport } from './routes/paramsparameter'
import { Route as NavigationblockRouteImport } from './routes/navigationblock'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as ItemsIdRouteImport } from './routes/items/$id'
import { Route as BlogIdRouteImport } from './routes/blog/$id'

const ParamsparameterRoute = ParamsparameterRouteImport.update({
  id: '/paramsparameter',
  path: '/paramsparameter',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationblockRoute = NavigationblockRouteImport.update({
  id: '/navigationblock',
  path: '/navigationblock',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/movies': typeof MoviesRoute
  '/navigationblock': typeof NavigationblockRoute
  '/paramsparameter': typeof ParamsparameterRoute
  '/blog/$id': typeof BlogIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/blog/': typeof BlogIndexRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/movies': typeof MoviesRoute
  '/navigationblock': typeof NavigationblockRoute
  '/paramsparameter': typeof ParamsparameterRoute
  '/blog/$id': typeof BlogIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/blog': typeof BlogIndexRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/movies': typeof MoviesRoute
  '/navigationblock': typeof NavigationblockRoute
  '/paramsparameter': typeof ParamsparameterRoute
  '/blog/$id': typeof BlogIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/blog/': typeof BlogIndexRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/movies'
    | '/navigationblock'
    | '/paramsparameter'
    | '/blog/$id'
    | '/items/$id'
    | '/products/$id'
    | '/blog/'
    | '/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/movies'
    | '/navigationblock'
    | '/paramsparameter'
    | '/blog/$id'
    | '/items/$id'
    | '/products/$id'
    | '/blog'
    | '/items'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/movies'
    | '/navigationblock'
    | '/paramsparameter'
    | '/blog/$id'
    | '/items/$id'
    | '/products/$id'
    | '/blog/'
    | '/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MoviesRoute: typeof MoviesRoute
  NavigationblockRoute: typeof NavigationblockRoute
  ParamsparameterRoute: typeof ParamsparameterRoute
  BlogIdRoute: typeof BlogIdRoute
  ItemsIdRoute: typeof ItemsIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paramsparameter': {
      id: '/paramsparameter'
      path: '/paramsparameter'
      fullPath: '/paramsparameter'
      preLoaderRoute: typeof ParamsparameterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigationblock': {
      id: '/navigationblock'
      path: '/navigationblock'
      fullPath: '/navigationblock'
      preLoaderRoute: typeof NavigationblockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MoviesRoute: MoviesRoute,
  NavigationblockRoute: NavigationblockRoute,
  ParamsparameterRoute: ParamsparameterRoute,
  BlogIdRoute: BlogIdRoute,
  ItemsIdRoute: ItemsIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
